config/routes.rb
Rails.application.routes.draw do

  default_url_options({host:'localhost:3000'})

  devise_for :users,
  defaults: { format: :json },
  path: '',
  path_names: {
    sign_in: 'api/login',
    sign_out: 'api/logout',
    registration: 'api/signup'
  },
  controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }


  scope '/api', defaults: { format: :json } do
    resources :courses
    resources :rooms
    resources :training_sessions
    resources :categories
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :index]
  end


  root to:"pages#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/training_session.rb
class TrainingSession < ApplicationRecord
    
    has_many :registrations
    has_many :students, class_name:"User", through: :registrations

    belongs_to :course

    belongs_to :room

    def api
        self.build("students")
    end
end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  before_action :set_training_session, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:update, :create, :destroy]

  # GET /training_sessions
  # GET /training_sessions.json
  def index
    @training_sessions = TrainingSession.all
  end

  # GET /training_sessions/1
  # GET /training_sessions/1.json
  def show
    render json: {training_sessions: @training_session, students: @training_session.students}
  end

  # GET /training_sessions/new
  def new
    @training_session = TrainingSession.new
  end

  # GET /training_sessions/1/edit
  def edit
  end

  # POST /training_sessions
  # POST /training_sessions.json
  def create
    @training_session = TrainingSession.new(training_session_params)
    @training_session.save
    render_jsonapi_response(@training_session)
    
  end

  # PATCH/PUT /training_sessions/1
  # PATCH/PUT /training_sessions/1.json
  def update
    respond_to do |format|
      if @training_session.update(training_session_params)
        format.html { redirect_to @training_session, notice: 'Training session was successfully updated.' }
        format.json {   render json: {training_sessions: @training_session, students: @training_session.students}   }
      else
        format.html { render :edit }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_sessions/1
  # DELETE /training_sessions/1.json
  def destroy
    @training_session.destroy
    respond_to do |format|
      format.html { redirect_to training_sessions_url, notice: 'Training session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training_session
      @training_session = TrainingSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_session_params
      params.require(:training_session).permit(:date, :room_id, :course_id, student_ids:[])
    end
end

app/helpers/training_sessions_helper.rb
module TrainingSessionsHelper
end

app/views/training_sessions/_form.html.erb
<%= form_with(model: training_session, local: true) do |form| %>
  <% if training_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training_session.errors.count, "error") %> prohibited this training_session from being saved:</h2>

      <ul>
        <% training_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/training_sessions/edit.html.erb
<h1>Editing Training Session</h1>

<%= render 'form', training_session: @training_session %>

<%= link_to 'Show', @training_session %> |
<%= link_to 'Back', training_sessions_path %>

app/views/training_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Training Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @training_sessions.each do |training_session| %>
      <tr>
        <td><%= training_session.date %></td>
        <td><%= link_to 'Show', training_session %></td>
        <td><%= link_to 'Edit', edit_training_session_path(training_session) %></td>
        <td><%= link_to 'Destroy', training_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training Session', new_training_session_path %>

app/views/training_sessions/new.html.erb
<h1>New Training Session</h1>

<%= render 'form', training_session: @training_session %>

<%= link_to 'Back', training_sessions_path %>

app/views/training_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @training_session.date %>
</p>

<%= link_to 'Edit', edit_training_session_path(@training_session) %> |
<%= link_to 'Back', training_sessions_path %>